name: dicom-labeler
channels:
  - conda-forge
dependencies:
  
  - python=3.13  
  - pip           
  - pydicom=3.0
  - numpy=2.3
  - pillow=11.3
  - flask=3.1
  - tqdm=4.67
  - pytest=8.4      
  - black=25.1       
  - pylibjpeg=2.0
  - pylibjpeg-libjpeg=2.3
  - pylibjpeg-openjpeg=2.4

  
